---
- hosts: all
  become: true
  tasks:
    - name: Ensure chrony is installed.
      yum: name=chrony state=present
    - name: Ensure chrony is runninig.
      service: name=chronyd state=started enabled=yes


